19-Rails-Validations/movie_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :characters
  resources :movies
  resources :actors

end

19-Rails-Validations/movie_app/app/models/actor.rb
class Actor < ApplicationRecord
    has_many :characters
    has_many :movies, through: :characters

end

19-Rails-Validations/movie_app/app/models/character.rb
class Character < ApplicationRecord
    belongs_to :movie
    belongs_to :actor

    validates(:role_name, {presence: true})
    # validates(:name, { presence: true, uniqueness: true })
end

19-Rails-Validations/movie_app/app/models/movie.rb
class Movie < ApplicationRecord
    has_many :characters
    has_many :actors, through: :characters
end

19-Rails-Validations/movie_app/app/controllers/actors_controller.rb
class ActorsController < ApplicationController

    def index
        @actors = Actor.all
    end

    def show
        @actor = Actor.find(params[:id])
    end

    def new
    end

    def create
    end

    def edit 
    end

    def update
    end
end

19-Rails-Validations/movie_app/app/controllers/characters_controller.rb
class CharactersController < ApplicationController

    def index 
        @characters = Character.all
    end

    def show
        @character = Character.find(params[:id])
    end

    def new
        @character = Character.new
        @movies = Movie.all
        @actors = Actor.all
    end
    
    def create
        byebug

        new_character = Character.new(char_params)

        if !new_character.valid? #if charcater is NOT valid, meaning the data is wrong 
        # if errors, redirect_to the new form WITH errors available to us for user to see
            # byebug
            flash[:errors] = new_character.errors.full_messages #add errors from model to our flash hash
            redirect_to new_character_path #redirect
        else
            new_character.save #save 
            redirect_to character_path(new_character) #go to show page of THAT character
        end
    end

    def char_params
        params.require(:character).permit(:role_name, :movie_id, :actor_id)
    end

end

19-Rails-Validations/movie_app/app/controllers/movies_controller.rb
class MoviesController < ApplicationController
    
    def index
        @movies = Movie.all
    end
    def show 
        @movie = Movie.find(params[:id])
    end

    def new
        @movie = Movie.new
        @actors = Actor.all
    end

    def create
        # byebug
        @movie = Movie.create(movie_params)

        # params[:movie][:actor_ids].reject(&:blank?).each do | id |
        #     Character.create(movie_id: @movie.id, actor_id: id )
        # end
        redirect_to movie_path(@movie)
    end

    def edit 
        @movie = Movie.find(params[:id])
        @actors = Actor.all
    end

    def movie_params
        params.require(:movie).permit(:title, :release_date)
    end
end

19-Rails-Validations/movie_app/app/helpers/actors_helper.rb
module ActorsHelper
end

19-Rails-Validations/movie_app/app/helpers/characters_helper.rb
module CharactersHelper
end

19-Rails-Validations/movie_app/app/helpers/movies_helper.rb
module MoviesHelper
end

19-Rails-Validations/movie_app/app/views/actors/index.html.erb
<h1>This is my index for actors</h1>

<% @actors.each do | a |%>
   <li> <%= link_to a.name, actor_path(a)%> </li>
<% end %>

19-Rails-Validations/movie_app/app/views/actors/show.html.erb
<h1><%= @actor.name%></h1>

<hr>
<h3>Roles played:   </h3>
<hr>
<ul>
<% @actor.characters.each do | char | %>
    <li> <%= link_to char.role_name, character_path(char) %> </li>
<% end %>


</ul>
<h3>movies this atcor has been in: </h3>
<ul>
<% @actor.movies.each do | movie | %>
    <li> <%= link_to movie.title, movie_path(movie) %> </li>
<% end %>


</ul>

19-Rails-Validations/movie_app/app/views/characters/_form.html.erb
<%= form_with model: @character do  | f | %>
<%= f.label :role_name %>
<%= f.text_field :role_name %>
<%= f.collection_select :movie_id, @movies, :id, :title, {include_blank: 'Select a Movie'}%>
<%= f.collection_select :actor_id, @actors, :id, :name, {include_blank: 'Select an Actor'} %>
<%= f.submit %>
<% end %>

19-Rails-Validations/movie_app/app/views/characters/index.html.erb
<h1>This is my index</h1>

<% @characters.each do | c |%>
   <li> <%= link_to c.role_name, character_path(c)%> </li>
<% end %>

19-Rails-Validations/movie_app/app/views/characters/new.html.erb
<% if flash[:errors] %>
<% flash[:errors].each do | error |%>
<li style="color:red"><%= error %> </li> 
<% end %>
<% end %>


<%= render 'form' %>

19-Rails-Validations/movie_app/app/views/characters/show.html.erb
<h1><%= @character.role_name%></h1>

<hr>
<h3>played by:  <%= @character.actor.name %> </h3>
<h3>in:  <%= @character.movie.title %> </h3>

19-Rails-Validations/movie_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MovieApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

19-Rails-Validations/movie_app/app/views/movies/_form.html.erb
<%= form_with model: @movie do  | f | %>
<%= f.label :title %>
<%= f.text_field :title %>
<%= f.label :release_date%>
<%= f.number_field :release_date%>
<%= f.collection_check_boxes :actor_ids, @actors, :id, :name %>
<%= f.submit %>
<% end %>

19-Rails-Validations/movie_app/app/views/movies/edit.html.erb
<%= render 'form' %>

19-Rails-Validations/movie_app/app/views/movies/index.html.erb
<h1>This is my movie index</h1>

<% @movies.each do | m |%>
   <li> <%= link_to m.title, movie_path(m)%> </li>
<% end %>

19-Rails-Validations/movie_app/app/views/movies/new.html.erb
<%= render 'form' %>

19-Rails-Validations/movie_app/app/views/movies/show.html.erb
<h1><%= @movie.title%></h1>