17-Rails-One-Many/cat_app/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/cats', to: 'cats#index'

  get '/cats/new', to: 'cats#new'
  # we need a show page
  get '/cats/:id', to: 'cats#show', as: 'cat'

  post '/cats', to: 'cats#create'

  # get '/someotherpage', to: 'controller#action', as: 'someotherprefix'

  get '/cats/:id/edit', to: 'cats#edit'

  patch '/cats/:id', to: 'cats#update'

  delete '/cats/:id', to: 'cats#destroy'


  # resources :cats, only: [:index, :show, :create, :update]

  resources :owners, only: [:index, :show]

  
end

17-Rails-One-Many/cat_app/app/models/cat.rb
class Cat < ApplicationRecord
    belongs_to :owner
end

17-Rails-One-Many/cat_app/app/models/owner.rb
class Owner < ApplicationRecord
    has_many :cats
end

17-Rails-One-Many/cat_app/app/controllers/cats_controller.rb
class CatsController < ApplicationController
    before_action :current_cat, only: [:show, :edit, :update, :destroy]

    def index 
        @cats = Cat.all 
    end

    def show 
        # @cat = Cat.find(params[:id])
        # byebug
    end
    #  create and update 
    def create
        # byebug
        if !params[:cat][:owner].empty?
            # create an owner 
            # THEN associate to cat
            new_owner = Owner.create(name: params[:cat][:owner])
            new_cat = Cat.create(cat_params)
            new_cat.owner = new_owner
            new_cat.save
        else
            new_cat = Cat.create(cat_params)
        end
    
        # posting some data
        redirect_to cat_path(new_cat)
    end

    def new
        @cat = Cat.new
        @owners = Owner.all
    end
    
    def edit    
        @owners = Owner.all
        # @cat = Cat.find(params[:id])
        # byebug
    end

    def update 
        # patching some data
        # @cat = Cat.find(params[:id])
        @cat.update(cat_params)

        # byebug
        redirect_to cat_path(@cat)
    end

    def destroy 
        # byebug
        # find cat 
        # cat = Cat.find(params[:id])
        # destroy cat
        @cat.destroy
        # go back to other cats 
        redirect_to cats_path
    end

    def current_cat
        @cat = Cat.find(params[:id])
    end

    def cat_params
        params.require(:cat).permit(:name, :breed, :age, :owner_id)
    end
end

17-Rails-One-Many/cat_app/app/controllers/owners_controller.rb
class OwnersController < ApplicationController

    def index
        @owners = Owner.all 
        # byebug
    end

    def show
        @owner = Owner.find(params[:id])
        # byebug
    end
end

17-Rails-One-Many/cat_app/app/helpers/cats_helper.rb
module CatsHelper
end

17-Rails-One-Many/cat_app/app/helpers/owners_helper.rb
module OwnersHelper
end

17-Rails-One-Many/cat_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

17-Rails-One-Many/cat_app/app/views/owners/index.html.erb
<h1>This is my owners index page</h1>

<% @owners.each do | owner |%>
<li> <%= link_to owner.name, owner_path(owner) %> </li>
<% end %>

17-Rails-One-Many/cat_app/app/views/owners/show.html.erb
<h1><%= @owner.name %></h1>

<h3>Cat list: </h3>
<% @owner.cats.each do | cat | %>
<li> <%= link_to cat.name, cat_path(cat) %> </li>
<% end %>

<%= link_to "Back to Owner's index", owners_path %>



<%= link_to "www.reddit.com", "https://www.reddit.com/" %>